version: '3.8'

services:
  dockeasy-app:
    container_name: dockeasy-app
    image: dockeasy-app:0.1
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dockeasy

networks:
  dockeasy:
    external: true
